"""empty message

Revision ID: 909343686d2a
Revises: 
Create Date: 2021-05-27 13:59:40.769926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '909343686d2a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usersmodel',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('casos',
    sa.Column('caso_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('decription', sa.Text(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['usersmodel.user_id'], ),
    sa.PrimaryKeyConstraint('caso_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('casos')
    op.drop_table('usersmodel')
    # ### end Alembic commands ###
